apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    role: myrole
spec:
  containers:
    - name: simple-webapp-color-container
      image: mmumshad/simple-webapp-color
      env:
        - name: APP_COLOR
          value: red
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
