apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      version: v2
  template:
    metadata:
      labels:
        app: nginx
        version: v2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
