apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      nodePort: 30303
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend  
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: eazy
        - name: WORDPRESS_DB_PASSWORD
          value: eazy
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-data-volume
          mountPath: /var/www/html
      volumes:
      - name: wordpress-data-volume
        hostPath:
          path: /data
          type: DirectoryOrCreate
