apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv
spec:
  containers:
    - name: mysql-volume-container
      image: mysql:latest
      env:
        - name: "MYSQL_USER"
          value: "eazy"
        - name: "MYSQL_PASSWORD"
          value: "eazy"
        - name: "MYSQL_DATABASE"
          value: "eazytraining"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "password"
      ports:
        - containerPort: 3306
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: pvc-vol1
